server.port=8815
spring.application.name=auth-service

# Eureka Service Discovery
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# Redis Configuration for Refresh Tokens
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}

# JWT Settings
jwt.secret=secretkey12345678901234567890123456789012345678901234567890
# 24 hours in milliseconds
jwt.access-token-expiration=86400000
# 7 days in milliseconds
jwt.refresh-token-expiration=604800000

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
