#Server port
server.port= 8900

#Application name
spring.application.name= api-gateway

#Client registration options :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

zuul.prefix=/api
zuul.ignored-services=*

# Ribbon timeouts
ribbon.ReadTimeout=60000
ribbon.ConnectTimeout=60000

# Eureka refresh
eureka.client.registry-fetch-interval-seconds=5

# Map paths to services
#----------------------------------
# Auth service :
zuul.routes.authservice.path=/auth/**
zuul.routes.authservice.service-id=auth-service

# User service :
zuul.routes.userservice.path=/accounts/**
zuul.routes.userservice.service-id=user-service

# Catalog service :
zuul.routes.catalogservice.path=/catalog/**
zuul.routes.catalogservice.service-id=product-catalog-service

# Order service :
zuul.routes.orderservice.path=/shop/**
zuul.routes.orderservice.service-id=order-service

# Recommendation service :
zuul.routes.recommendationservice.path=/review/**
zuul.routes.recommendationservice.service-id=product-recommendation-service

#SPRING SESSION & REDIS PROPERTIES :
#-------------------------------
spring.session.store-type=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

#SECURITY
#---------------------------------
zuul.sensitive-headers=

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



